---
- name: working on docker containers
  hosts: all
  tasks:
   - name: create a tomcat docker container
     docker_container: 
      name: webserver
      image: tomee
   - name: stop the tomcat container
     docker_container:
      name: webserver
      state: stopped
   - name: delete the tomcat container
     docker_container:
      name: webserver
      state: absent
...
