---
- name: ssetup of docker and dependent s/w
  hosts: all
  tasks:
   - name: install python-pip
     apt:
      name: python3-pip
      state: present
      update_cache: yes
   - name: download docker shell script
     shell: curl -fsSL https://get.docker.com -o get-docker.sh
   - name: execute the shell script
     shell: sh get-docker.sh
   - name: install docker-py
     shell: pip3 install docker-py
...
