--- 
- name: setup of docker and depedent s/w's
  hosts: all
  tasks:
   - name: install python-pip
     apt:
      name: python3-pip
      state: present
      update_cache: yes
   - name: download docker shell script  and execute it and install docker-py
     shell: "{{item}}"
     with_items:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - pip3 install docker-py
...
