---
- name: implementing docker compose using ansible
  hosts: all
  tasks:
   - name: create mysql container
     docker_container:
      name: mydb
      image: mysql:5
      env:
       MYSQL_ROOT_PASSWORD: mahender
   - name: create a wordpress container
     docker_container:
      name: mywordpress
      image: wordpress
      ports:
       - 9090:80
      links:
       - mydb:mysql
...
